name: Runner

on:
  push:
    branches: [main]

jobs:
  manage-org-member:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: yarn install
      - run: yarn start
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
